name: CI function-tatsukoni-test-v8

on:
  push:
    paths:
      - ".github/workflows/**"
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './api' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "Install Dependencies"
        run: |
          npm install

      - name: "Build"
        shell: bash
        run: |
          npm run build --if-present

      - name: "Test"
        shell: bash
        run: |
          npm run test --if-present
